### ISSUE TITLE
got ExternalReferenceException but there's no external reference in document

### ISSUE THREAD

**Issue by kubido** [tamc/excel_to_code#15]
Hi,

I got error message **'Named reference xiv.a.area [1]Control!E62 not parsed**

> /Users/myname/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/excel_to_code-0.3.13/src/rewrite/caching_formula_parser.rb:93:in `external_reference': ExternalReferenceException

in my sheets "xiv.a" cell E62. it's just an empty cell. I've try to remove the related sheets. and remove all sheets and leave one sheet. still get the same error

**Comment by tamc** [comment]
This relates to a named reference. Take a look in the name manager in excel for a named reference called xiv.a.area and you should see it as linked to an external worksheet.You should be able to change it to point at the local worksheet there.

**Comment by tamc** [comment]
Issue hasn't been updated in a while. Closing.
