### ISSUE TITLE
Error trying to convert my spreadsheet.

### ISSUE THREAD

**Issue by Pistorius** [tamc/excel_to_code#17]
Hi, im trying to conver a xlsx file to c with this code
```
command = ExcelToC.new
command.excel_file = 'my_path_file'
command.output_directory = 'my_path_output'
command.output_name = 'test_model_c'
command.named_references_that_can_be_set_at_runtime = { "Control" => (44.upto(117).to_a.map { |r| "f#{r}" }) }

command.cells_to_keep = {
  "Resultados Intermedios" => :all, 
}
command.actually_compile_code = true
command.actually_run_tests = true
command.go!
```
As result i get this trace
```
16:51   Excel to Code version 0.3.17

16:51   Removing any old xml
bin/rails: No such file or directory - unzip -q 'c:/sites/calculator2050/docs/model/modelo_prueba.xlsx' -d 'C:/User
DRI~1/AppData/Local/Temp/d20170829-3496-1aaihpy'
16:51   Unziping excel into xml
16:51   Extracting shared strings
16:51   C:/Users/PRODRI~1/AppData/Local/Temp/d20170829-3496-1aaihpy/xl/sharedStrings.xml does not exist in xml(["sh
trings.xml"]), using blank instead
16:51   Extracting named references
16:51   C:/Users/PRODRI~1/AppData/Local/Temp/d20170829-3496-1aaihpy/xl/workbook.xml does not exist in xml(["workboo
"]), using blank instead
16:51   Extracting worksheet names
16:51   C:/Users/PRODRI~1/AppData/Local/Temp/d20170829-3496-1aaihpy/xl/workbook.xml does not exist in xml(["workboo
"]), using blank instead
16:51   C:/Users/PRODRI~1/AppData/Local/Temp/d20170829-3496-1aaihpy/xl/_rels/workbook.xml.rels does not exist in xm
rels", "workbook.xml.rels"]), using blank instead
16:51   Extracting Tables
16:51   Cells to keep includes :"Resultados Intermedios" but could not be found in workbook: []
Completed 500 Internal Server Error in 156ms
```
Is there something im doing wrong?

[Here ](https://www.dropbox.com/s/kayz2u6i9blbpyi/modelo_prueba.xlsx?dl=0)is my xlsx file in case of...

**Comment by Pistorius** [comment]
Hi, finally I can start to parse my file but getting some error with formula INDIRECT.

Here is the error:
```
Exception at [:"XV.b", :G15] [:prefix, "-", [:function, :INDEX, [:function, :INDIRECT, [:string_join, [:constant, "constant4596"], [:sheet_reference, :"XV.b", [:cell, :G14]], [:constant, "constant4597"]]], [:function, :MATCH, [:sheet_reference, :"XV.b", [:cell, :C15]], [:function, :INDIRECT, [:string_join, [:constant, "constant4596"], [:sheet_reference, :"XV.b", [:cell, :G14]], [:constant, "constant4598"]]], [:number, 0.0]]]]
Completed 500 Internal Server Error in 250461ms



NotSupportedException (Function INDIRECT with 1 arguments not supported):
```
After to see this error i went to the cell referenced and the formula is like this:
`=-INDICE(INDIRECTO("'"&G$14&"'!ano.balanceneto"); COINCIDIR($C15; INDIRECTO("'"&G$14&"'!ano.vector"); 0))`
But im not sure about what is wrong, it suppuosed the formula is like on of the formulas in the model of UK, who used this parser too without this trouble.

Please i need some help here

**Comment by Pistorius** [comment]
The updated file with no external references is [here](https://www.dropbox.com/s/jd5f7srjgrfww4u/modelo_prueba%20updated.xlsx?dl=0)

**Comment by tamc** [comment]
Hello

Sorry for the delay in replying. I was on holiday.

I've downloaded your spreadsheet from the link above and saved it as model.xlsx

I then did  `gem install excel_to_code`

I then ran this script:

    require 'excel_to_code'
    command = ExcelToC.new
    command.excel_file = 'model.xlsx'
    command.output_directory = '.'
    command.output_name = 'test_model_c'
    command.cells_that_can_be_set_at_runtime = { "Control" => (44.upto(117).to_a.map { |r| "f#{r}" }) }

    command.cells_to_keep = {
      "Resultados Intermedios" => :all, 
    }
    command.actually_compile_code = true
    command.actually_run_tests = true
    command.go!

After a few minutes, the script ended with:

    3307 runs, 3307 assertions, 0 failures, 0 errors, 0 skips

I did not see any INDIRECT errors. Could you tell me what you did differently? Or was the error at some other point?

**Comment by Pistorius** [comment]
Hi, i'm doing exactly the same, maybe with some differences but trying to executing the same code here i got the same result. When excel_to_code print the part of "Writing C code..." i got this tail of trace: 

```
16:33   Extracting data from Sector Agropecuario
16:33   Extracting data from Sector Forestal
16:33   Extracting data from Listas
16:33   Extracting Tables
16:33   Transfering named references to keep into cells to keep
16:33   Making sure there are setter methods for named references that can be set
16:33   Named reference ["Control", ["f44", "f45", "f46", "f47", "f48", "f49", "f50", "f51", "f52", "f53", "f54", "f55", "f56", "f57", "f58", "f59", "f60", "f61", "f62", "f63", "f64", "f65", "f66", "f67", "f68", "f69", "f70", "f71", "f72", "f73", "f74", "f75", "f76", "f77", "f78", "f79", "f80", "f81", "f82", "f83", "f84", "f85", "f86", "f87", "f88", "f89", "f90", "f91", "f92", "f93", "f94", "f95", "f96", "f97", "f98", "f99", "f100", "f101", "f102", "f103", "f104", "f105", "f106", "f107", "f108", "f109", "f110", "f111", "f112", "f113", "f114", "f115", "f116", "f117"]] not found
16:33   Rewriting values
16:33   Rewriting row and column references
16:33   Rewriting shared formulae
16:33   Expanding 0 array formulae
16:33   Rewriting array formulae into conventional formulae
16:33   Combining formulae types
16:33   Checking required references
16:33   Sheet contains 110684 cells
16:33   Simplifying arithmetic
16:33   Simplifying cells
16:33   Generating a good set of cells that should be settable
16:34   Working out which named references can be set at runtime
16:34   Filtering named references to keep
16:34   Starting pass 1 on 47110 cells
16:34   Simplifying cells
16:34   Pass 1: Made 17224 replacements
16:34   Starting pass 2 on 45287 cells
16:35   Simplifying cells
16:35   Pass 2: Made 10 replacements
16:35   Starting pass 3 on 45287 cells
16:35   Simplifying cells
16:35   Pass 3: Made 0 replacements
16:35   Inlining formulae
16:36   Removing cells not needed for outputs
16:39   Looking for repeated bits of formulae

16:39   Replacing values with constants
16:39   Creating references to test
16:39   Writing C code
Exception at [:"XV.b", :G15] [:prefix, "-", [:function, :INDEX, [:function, :INDIRECT, [:string_join, [:constant, "constant4596"], [:sheet_reference, :"XV.b", [:cell, :G14]], [:constant, "constant4597"]]], [:function, :MATCH, [:sheet_reference, :"XV.b", [:cell, :C15]], [:function, :INDIRECT, [:string_join, [:constant, "constant4596"], [:sheet_reference, :"XV.b", [:cell, :G14]], [:constant, "constant4598"]]], [:number, 0.0]]]]
Completed 500 Internal Server Error in 250461ms



NotSupportedException (Function INDIRECT with 1 arguments not supported):
```
As i can see in the workbook im using the INDIRECT formula as same as UK calculator did.

By other way im using `ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]` and working by "Bash on Ubuntu on Windows". The ubuntu version is:
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

**Comment by tamc** [comment]
Check the line: 

    command.cells_that_can_be_set_at_runtime = { "Control" => (44.upto(117).to_a.map { |r| "f#{r}" }) }

You must be using something different.

**Comment by Pistorius** [comment]
You are right!, i was trying
`command.named_references_that_can_be_set_at_runtime = { "Control" => (44.upto(117).to_a.map { |r| "f#{r}" }) }`
instead that
Thank a lot @tamc !

**Comment by Pistorius** [comment]
@tamc 
I have one question more, after convert my file to code im trying to set a value in spreadsheet "Control" from 1 to 2 with `set_control_f44(2)`. At this point everything is ok, the value of f44 changed from 1 to 2 with that method. But then when i want to check the recalculed value from another spreadsheet ("Resultados intermedios") with `resultados_intermedios_z15` the value was not recalculated :/
Im missing something?

**Comment by tamc** [comment]
I'm guessing you did:

    resultados_intermedios_z15() <- Correct
    set_control_f44(2)
    resultados_intermedios_z15() <- Unchanged

What you need to do is:

    resultados_intermedios_z15() <- Correct
    reset() <- IMPORTANT
    set_control_f44(2)
    resultados_intermedios_z15() <- Correct

The sequence should always be:

1. reset
2. set values
3. read values

This is because the results are cached. They are cached for speed.

**Comment by Pistorius** [comment]
Now im in peace. Thanks again @tamc !
